### ISSUE TITLE
How do we pick where the smooth component begins

### ISSUE THREAD

**Issue by eteq** [robelgeda/dsii_dwarfs#11]
Because it's easy given the way the isochrones are stored, just saying "main sequence is smooth", "RGB is not" is easy for now. But for e.g. star-forming galaxies that's not sufficient because the brightest stars are probably BSG or RSG stars (which are MS).  So we should consider how to have a slightly better definition of the "smooth" component.

Fiducial idea: define a "pixel" for a given galaxy (or an average density), work down the IMF with random samples, and when you hit a certain number (10? 100?) of stars in that one pixel, that's the cutoff.  Repeat 1000x, and pick the median of that answer.

**Comment by hcferguson** [comment]
For now I'm picking 1 solar mass or the MS turnoff , whichever is smaller. I think this should catch the case of young stellar populations.

**Comment by hcferguson** [comment]
Closed by #17 implementing the simple shortcut described in [my comment](https://github.com/robelgeda/dsii_dwarfs/issues/11#issuecomment-508814323) above. Can open a new issue if we decide to do something fancier.
