### ISSUE TITLE
Isochrone Picker 

### ISSUE THREAD

**Issue by robelgeda** [robelgeda/dsii_dwarfs#2]
Given an age in metallicity chose the isochrone file name.

**Comment by hcferguson** [comment]
Created a notebook to select a metallicity from the Kirby+13 Mass-metallicity relation, and an age from a Gaussian with a mean age of 11 Gyr and a scatter of 2 Gyr. It will read the closest isochrone file in metallicity and select out the nearest age.  PR #22.

**Comment by hcferguson** [comment]
Implemented in `isochrone_picker.py` in PR #25.
