### ISSUE TITLE
Dealing with varying PSFs

### ISSUE THREAD

**Issue by hcferguson** [robelgeda/dsii_dwarfs#23]
In the case of HSC and LSST data, the PSF will vary significantly from image to image. But in both cases the calibration pipeline will produce a PSF for us. So we probably ought to train on sets of images that are paired with their PSFs.

**Comment by hcferguson** [comment]
@brechmos-stsci would it be better to do this from the outset, or start with a fixed PSF first? It's  easy to make the simulations drawing from random Moffat PSFs with a range of parameters.

**Comment by hcferguson** [comment]
A related question is whether it might be better to have a library of oversampled noiseless images in each band, a library of PSFs for each band, and a library of noise (models) for each band. Then convolve and add noise using permutations from the library before doing the training.

**Comment by robelgeda** [comment]
We now use PSF's from HSC's API for a given band at a given RA and DEC.
