### ISSUE TITLE
 Many of the galaxies overfill the postage stamps

### ISSUE THREAD

**Issue by hcferguson** [robelgeda/dsii_dwarfs#26]
Double-check the sizes, but probably they are okay. If so, we should. Since we are eventually just going to be adding the to much bigger Subaru images, we might not need to get the neural-network to work with bigger postage stamps, but just move over to the one that works on scanning the big images.

**Comment by hcferguson** [comment]
I've double-checked the sizes, calculating by hand rather than using the astropy.cosmology routines. I think they are correct.

**Comment by robelgeda** [comment]
We are fixing this by cutting off overfilling galaxies at the pixel at which the flux is equal to the STD  of the noise in the HSC images. I am applying an `auto_npix` flag which will expand the images in this way if they overfill. An image size upper limit is also implemented to prevent images from getting too large.
