### ISSUE TITLE
Get more HSC PSF statistics

### ISSUE THREAD

**Issue by hcferguson** [robelgeda/dsii_dwarfs#27]
Download a bunch of HSC PSFs (I think there is an API for this), being careful to separate those for the wide, deep and ultra deep portions of the survey. Measure their Moffat parameters for each of the individual g,r,i,z,& y bands, and put them in a table. Look for trends in gamma & alpha with wavelength. Save some measure of goodness of fit as well, since it would be nice to know if the Moffat is a decent model.

Keep the PSFs around because we may down the road need to change from a Moffat to something else.

**Comment by robelgeda** [comment]
We directly download the PSF images from the HSC website via their API
