### ISSUE TITLE
Get more info on HSC background noise trends

### ISSUE THREAD

**Issue by hcferguson** [robelgeda/dsii_dwarfs#28]
Download a bunch of HSC images (there may be an API for this), and measure the background noise levels in each wavelength, being sure to separate the wide from the deep from the ultra-deep portions of the survey. I usually use the sigma_clipped and mad_std statistics in astropy for this. Put in a table along with the info on filter and exposure time. 
We are mostly interested in the co-adds. 

Look at the trends in noise level vs. band for each exposure depth. 

This is important if we are going to make more postage stamps. It's not particularly important if we are just going to jump to inserting the images into the real HSC images.

**Comment by robelgeda** [comment]
This was done in `Noise.ipynb` though only for one of the data types:
```
17130: G mad_std:  0.017740549355562473
8283:  G mad_std:  0.044103222204375826
17130: R mad_std:  0.02990474870732612
8283:  R mad_std:  0.06527874300441547
17130: I mad_std:  0.038061441331219865
8283:  I mad_std:  0.1429576608190141
17130: Z mad_std:  0.060185003546121545
8283:  Z mad_std:  0.17481671712569938
17130: Y mad_std:  0.1398606023648071
8283:  Y mad_std:  0.43618016343062577
```
