### ISSUE TITLE
Galaxy Mass Picker 

### ISSUE THREAD

**Issue by robelgeda** [robelgeda/dsii_dwarfs#3]
Draw a galaxy at mass at random from Schechter function.

**Comment by robelgeda** [comment]
Use -1.3 as a guess for the faint end slope and a mass of 1e10 as the characteristic mass.
The -1.3 is the alpha.

**Comment by robelgeda** [comment]
### Note:
This person made a function for sampling from the Schecther function:
https://gist.github.com/joezuntz/5056136

**Comment by hcferguson** [comment]
Used that one after a bunch of deadends trying scipy...PR #21

**Comment by robelgeda** [comment]
![Screenshot_20190702-204609_Adobe Acrobat](https://user-images.githubusercontent.com/10345916/62069400-2f064a00-b206-11e9-9a67-c804defc5078.jpg)
![Screenshot_20190702-204623_Adobe Acrobat](https://user-images.githubusercontent.com/10345916/62069411-34639480-b206-11e9-8223-ae0d4a11ed5f.jpg)


We can use inverse transform sampling using the functions above to generate the random numbers. Its now clear to me that this is what the link above is doing.

**Comment by robelgeda** [comment]
Closed by #21 
#21 looks good to me!
