### ISSUE TITLE
Star Mass Picker 

### ISSUE THREAD

**Issue by robelgeda** [robelgeda/dsii_dwarfs#4]
Draw a star mass from at random from an initial stellar mass function:
Draw star masses at random from an initial mass function 
     - There is a package for this https://github.com/keflavich/imf. One could also do this with Astropy models no doubt, but that would require more thought.
     - need to decide on a lower mass limit for this so we don't spend all our time on stars that don't contribute to fluctuations. Add those in as one additional smooth component, with the right total flux relative to the stars we have added individually.
     - draw enough stars that the total mass of the smooth + individual components adds up to the total mass you want for the dwarf galaxy.
     - $N_{indiv}$ is the total number of individual stars

[M Priority]

**Comment by hcferguson** [comment]
This is implemented in `HSC_dwarf_simulation.ipynb` PR #17.
