### ISSUE TITLE
Galaxy Surface Brightness Profile Picker

### ISSUE THREAD

**Issue by robelgeda** [robelgeda/dsii_dwarfs#5]
Choose a 2D model profile for the galaxy
     - Typically, these galaxies have Sersic profiles with n ~ 1, half-light radii of ~ 0.5-1 kpc and axial ratios between 0.5 and 1
     - We will ultimately want to draw these from distribution functions (there are some in the literature)
     - This should be oversampled by at least a factor of 4 relative to the pixel sampling of the telescope/survey of choice (e.g. WFIRST, LSST or HSC).

**Comment by hcferguson** [comment]
Split the axial ratio picker off into #18 and created a notebook #19 to implement it.

**Comment by hcferguson** [comment]
Looks like a linear fit to an empirical size distribution, with some scatter will suffice. PR #20.

**Comment by hcferguson** [comment]
I'm happy with this. Closing the issue.
